name: thermal-simulation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fenics
  - numpy>=1.19.0
  - matplotlib>=3.3.0
  - scipy>=1.6.0
  - pandas>=1.2.0
  - mpi4py>=3.0.0
  - openmpi
  - pip
  - pip:
    - pytest>=6.0.0
    - flake8>=3.8.0